In [2]:
import numpy as np

In [3]:
data1 = [6,7.5,8,0,1]
arr1 = np.array(data1)

In [4]:
arr1

array([ 6. ,  7.5,  8. ,  0. ,  1. ])

In [5]:
data2 = [[1,2,3,4],[5,6,7,8]]

In [6]:
arr2 = np.array(data2)

In [7]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [8]:
arr2.shape

(2, 4)

In [9]:
np.zeros(10)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [10]:
np.zeros((3,6))

array([[ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.]])

In [11]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [12]:
np.eye(4)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [13]:
arr = np.array([1,2,3,4,5])
arr.dtype

dtype('int64')

In [14]:
float_arr = arr.astype(np.float64)

In [15]:
float_arr.dtype

dtype('float64')

In [16]:
numeric_strings = np.array(['1.25','-9.6','42'], dtype= np.string_)

In [17]:
numeric_strings.astype(float)

array([  1.25,  -9.6 ,  42.  ])

In [18]:
arr = np.array([[1.,2.,3.], [4.,5.,6.]])

In [19]:
arr

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.]])

In [20]:
arr * arr

array([[  1.,   4.,   9.],
       [ 16.,  25.,  36.]])

In [21]:
arr - arr

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [22]:
arr = np.arange(10)

In [23]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
arr[5]

5

In [25]:
arr[5:8]

array([5, 6, 7])

In [26]:
arr[5:8] = 12

In [27]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [28]:
arr_slice = arr[5:8]

In [29]:
arr_slice

array([12, 12, 12])

In [30]:
arr_slice[1]

12

In [31]:
arr_slice[1] = 12345    

In [32]:
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,     9])

In [33]:
arr[1:6]

array([ 1,  2,  3,  4, 12])

In [34]:
arr2d = np.array([[1,2,3],[4,5,6], [7,8,9]])

In [35]:
arr2d[2]

array([7, 8, 9])

In [36]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [37]:
arr2d[:2,1:]

array([[2, 3],
       [5, 6]])

In [38]:
arr2d[0,1]

2

In [39]:
from numpy import random
names = np.array(['Bob', 'Joe','Will','Bob','Will','Joe', 'Joe'])
data = random.randn(7,4)

In [40]:
data

array([[ 0.16986937, -1.19482045,  2.17758108, -0.27980849],
       [-2.03791506,  1.03696178,  1.1713292 , -0.97729857],
       [-0.54084804,  0.70949547, -0.73908078,  0.28324439],
       [ 2.55237927, -0.63486051,  0.60564029, -0.91504228],
       [-0.22601872,  0.59879271,  1.38092494,  0.76031555],
       [-0.93357611,  0.960518  ,  2.68180286,  1.3453371 ],
       [ 0.42278081, -0.61445591, -0.34179487,  0.4933775 ]])

In [41]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], 
      dtype='|S4')

In [42]:
names == 'Bob'

array([ True, False, False,  True, False, False, False], dtype=bool)

In [43]:
data[names == 'Bob']

array([[ 0.16986937, -1.19482045,  2.17758108, -0.27980849],
       [ 2.55237927, -0.63486051,  0.60564029, -0.91504228]])

In [44]:
data[names == 'Bob', 2:]

array([[ 2.17758108, -0.27980849],
       [ 0.60564029, -0.91504228]])

In [45]:
data[names == 'Bob', 3]

array([-0.27980849, -0.91504228])

In [46]:
names != 'Bob'

array([False,  True,  True, False,  True,  True,  True], dtype=bool)

In [47]:
data[-(names == 'Bob')]

/home/caztillo/anaconda2/lib/python2.7/site-packages/ipykernel/__main__.py:1: DeprecationWarning: numpy boolean negative, the `-` operator, is deprecated, use the `~` operator or the logical_not function instead.
  if __name__ == '__main__':


array([[-2.03791506,  1.03696178,  1.1713292 , -0.97729857],
       [-0.54084804,  0.70949547, -0.73908078,  0.28324439],
       [-0.22601872,  0.59879271,  1.38092494,  0.76031555],
       [-0.93357611,  0.960518  ,  2.68180286,  1.3453371 ],
       [ 0.42278081, -0.61445591, -0.34179487,  0.4933775 ]])

In [50]:
data[~(names == 'Bob')]

array([[-2.03791506,  1.03696178,  1.1713292 , -0.97729857],
       [-0.54084804,  0.70949547, -0.73908078,  0.28324439],
       [-0.22601872,  0.59879271,  1.38092494,  0.76031555],
       [-0.93357611,  0.960518  ,  2.68180286,  1.3453371 ],
       [ 0.42278081, -0.61445591, -0.34179487,  0.4933775 ]])

In [51]:
mask = (names == 'Bob') | (names == 'Will')

In [52]:
mask

array([ True, False,  True,  True,  True, False, False], dtype=bool)

In [53]:
data[names != 'Joe'] = 7

In [54]:
data

array([[ 7.        ,  7.        ,  7.        ,  7.        ],
       [-2.03791506,  1.03696178,  1.1713292 , -0.97729857],
       [ 7.        ,  7.        ,  7.        ,  7.        ],
       [ 7.        ,  7.        ,  7.        ,  7.        ],
       [ 7.        ,  7.        ,  7.        ,  7.        ],
       [-0.93357611,  0.960518  ,  2.68180286,  1.3453371 ],
       [ 0.42278081, -0.61445591, -0.34179487,  0.4933775 ]])

In [55]:
arr = np.empty((8,4))

In [56]:
for i in range(8):
    arr[i] = i

In [57]:
arr

array([[ 0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  4.],
       [ 5.,  5.,  5.,  5.],
       [ 6.,  6.,  6.,  6.],
       [ 7.,  7.,  7.,  7.]])

In [58]:
arr = np.arange(32).reshape((8 ,4))

In [59]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [60]:
arr[[1,5,7,2],[0,3,1,2]]

array([ 4, 23, 29, 10])

In [61]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [62]:
arr = np.arange(15).reshape((3,5))

In [63]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [64]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [65]:
arr = np.random.randn(6,3)

In [66]:
np.dot(arr.T, arr)

array([[ 4.57498963, -1.23930133,  0.35889316],
       [-1.23930133,  3.50218224, -0.73424423],
       [ 0.35889316, -0.73424423,  3.4287364 ]])

In [67]:
arr = np.arange(10)

In [68]:
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ])

In [69]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [70]:
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03])

In [74]:
x = random.randn(8)
y= random.randn(8)


In [75]:
x
y

array([-0.72356099, -0.37986336,  1.69137094,  1.22349297,  0.57497744,
        0.32887957, -1.13174266,  0.56089247])

In [76]:
x

array([-0.19046275, -0.54352987, -0.40850528, -0.14069983, -0.40080968,
        0.83522093,  0.01096395,  0.77242753])

In [77]:
y

array([-0.72356099, -0.37986336,  1.69137094,  1.22349297,  0.57497744,
        0.32887957, -1.13174266,  0.56089247])

In [78]:
np.maximum(x,y)

array([-0.19046275, -0.37986336,  1.69137094,  1.22349297,  0.57497744,
        0.83522093,  0.01096395,  0.77242753])

In [80]:
arr = random.randn(7) * 5

In [81]:
arr

array([-0.15323243,  2.51621345,  0.88553286,  4.81581601,  0.4197273 ,
       -5.97989745,  0.29967366])

In [82]:
np.modf(arr)

(array([-0.15323243,  0.51621345,  0.88553286,  0.81581601,  0.4197273 ,
        -0.97989745,  0.29967366]), array([-0.,  2.,  0.,  4.,  0., -5.,  0.]))

In [83]:
xarr = np.array([1.1,1.2,1.3,1.4,1.5])
yarr = np.array([2.1,2.2,2.3,2.4,2.5])

In [84]:
cond = np.array([True,False,True,True,False])

In [85]:
result = np.where(cond,xarr,yarr)

In [86]:
result

array([ 1.1,  2.2,  1.3,  1.4,  2.5])

In [87]:
arr = random.randn(4,4)

In [88]:
arr

array([[-0.13631236, -0.23555488, -2.26832125, -1.91488108],
       [-1.13028282, -0.35948007,  1.58609986, -2.60200275],
       [-0.60329249,  0.61359911,  1.29350359,  0.69978908],
       [-1.20968042,  1.55735585, -1.55802523, -1.00752888]])

In [89]:
np.where(arr > 0, 2, -2)

array([[-2, -2, -2, -2],
       [-2, -2,  2, -2],
       [-2,  2,  2,  2],
       [-2,  2, -2, -2]])

In [91]:
#np.where(cond1 & cond2, 0, np.where(cond1, 1, np.where(cond2,2,3)))

In [92]:
arr = np.random.randn(5,4)

In [93]:
arr

array([[-2.12308775,  1.41583336, -0.42763867,  0.00419462],
       [ 1.43818411,  0.42362172,  1.12452827, -1.00684408],
       [-0.98079271,  1.58070941, -0.12047173,  0.36276283],
       [ 2.68874187, -0.85461258, -2.32846735,  2.4977621 ],
       [ 0.05233922, -1.17234636, -0.29317083,  0.69231354]])

In [94]:
arr.sum()

2.9735590076315161

In [95]:
arr.sum(0)

array([ 1.07538475,  1.39320555, -2.0452203 ,  2.55018901])

In [96]:
-2.12308775+1.43818411+-0.98079271+2.68874187+0.05233922

1.0753847399999998

In [97]:
arr

array([[-2.12308775,  1.41583336, -0.42763867,  0.00419462],
       [ 1.43818411,  0.42362172,  1.12452827, -1.00684408],
       [-0.98079271,  1.58070941, -0.12047173,  0.36276283],
       [ 2.68874187, -0.85461258, -2.32846735,  2.4977621 ],
       [ 0.05233922, -1.17234636, -0.29317083,  0.69231354]])

In [98]:
arr.sort()

In [99]:
arr

array([[-2.12308775, -0.42763867,  0.00419462,  1.41583336],
       [-1.00684408,  0.42362172,  1.12452827,  1.43818411],
       [-0.98079271, -0.12047173,  0.36276283,  1.58070941],
       [-2.32846735, -0.85461258,  2.4977621 ,  2.68874187],
       [-1.17234636, -0.29317083,  0.05233922,  0.69231354]])

In [100]:
arr = random.randn(5,3)

In [101]:
arr

array([[-0.60574941,  0.34162449, -0.32309829],
       [ 0.18968317, -0.11183699,  0.42742129],
       [ 0.97363604,  0.42835859, -0.22555318],
       [ 1.19726245,  1.41029297, -1.89750348],
       [-0.39483849, -1.28995045, -1.34659232]])

In [102]:
arr.sort(1)

In [103]:
arr

array([[-0.60574941, -0.32309829,  0.34162449],
       [-0.11183699,  0.18968317,  0.42742129],
       [-0.22555318,  0.42835859,  0.97363604],
       [-1.89750348,  1.19726245,  1.41029297],
       [-1.34659232, -1.28995045, -0.39483849]])

In [104]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

In [105]:
np.unique(names)

array(['Bob', 'Joe', 'Will'], 
      dtype='|S4')

In [106]:
arr = np.arange(10)

In [107]:
np.save('some_array',arr)

In [108]:
np.load('some_array.npy')

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [109]:
!cat array_ex.txt

cat: array_ex.txt: No such file or directory


In [110]:
x = np.array([[1.,2.,3.],[4.,5.,6.]])
y = np.array([[6.,23.],[-1,7], [8,9]])

In [111]:
x

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.]])

In [112]:
y

array([[  6.,  23.],
       [ -1.,   7.],
       [  8.,   9.]])

In [113]:
x.dot(y)

array([[  28.,   64.],
       [  67.,  181.]])

In [114]:
from random import normalvariate

In [115]:
N = 1000000

In [116]:
%timeit samples = [normalvariate(0,1) for _ in xrange(N)]

1 loop, best of 3: 2.86 s per loop


In [117]:
%timeit np.random.normal(size=N)

10 loops, best of 3: 111 ms per loop


In [118]:
import random
position = 0
walk = [position]
steps = 1000
for i in xrange(steps):
    step = 1 if random.randint(0,1) else -1
    position += step
    walk.append(position)

In [119]:
nwalks = 5000
nsteps = 1000
draws = np.random.randint(0,2,size=(nwalks,nsteps))
steps = np.where (draws > 0, 1, -1)
walks = steps.cumsum(1)
walks

array([[ -1,   0,   1, ...,  16,  17,  18],
       [ -1,  -2,  -1, ..., -22, -23, -24],
       [ -1,   0,   1, ...,  -8,  -9,  -8],
       ..., 
       [ -1,   0,  -1, ..., -60, -59, -58],
       [  1,   2,   3, ...,  -8,  -7,  -6],
       [ -1,  -2,  -3, ...,  24,  23,  24]])

In [120]:
walks.max()

124

In [121]:
walks.min()

-124

In [122]:
hits30 = (np.abs(walks) >= 30).any(1)

In [123]:
hits30

array([False,  True, False, ...,  True,  True,  True], dtype=bool)

In [124]:
hits30.sum()

3401

In [125]:
crossing_times = (np.abs(walks[hits30]) >= 30).argmax(1)

In [127]:
crossing_times.mean()

499.51161423110852